[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_dice_game = "8TdE8ycHXpH1FBUpUTpZK5gCCppZ1yGyesvKv5JFvSXG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

# Orao VRF localnet deployment
[[tests.genesis]]
address = "VRFzZoJdhFWL8rkvu87LpKM3RbcVezpMEc6X5GVDr7y"
program = "lib/orao_vrf.so"
