name: "Setup Solana"
description: "Setup Solana"
runs:
  using: "composite"
  steps:
    - run: echo "before cache action, cache hit"
      if: steps.cache-solana.outputs.cache-hit != 'true'
    - uses: actions/cache@v3
      name: Cache Solana Tool Suite
      id: cache-solana
      with:
        path: |
          ~/.cache/solana/
          ~/.local/share/solana/
        key: solana-${{ runner.os }}-v0000-${{ env.SOLANA_CLI_VERSION }}-${{ env.SOLANG_VERSION }}
    - run: echo "after cache action, cache hit"
      if: steps.cache-solana.outputs.cache-hit != 'true'
      shell: bash
    - run: echo "before retry action, cache hit"
      if: steps.cache-solana.outputs.cache-hit != 'true'   
      shell: bash
    - uses: nick-fields/retry@v2
      if: steps.cache-solana.outputs.cache-hit != 'true'
      shell: bash
      with:
        retry_wait_seconds: 300
        timeout_minutes: 2
        max_attempts: 10
        retry_on: error
        shell: bash
        command: sh -c "$(curl -sSfL https://release.anza.xyz/v${{ env.SOLANA_CLI_VERSION }}/install)"
    - run: echo "after retry action, cache hit"
      if: steps.cache-solana.outputs.cache-hit != 'true'
      shell: bash
    - run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      shell: bash
    - run: solana-keygen new --no-bip39-passphrase
      shell: bash
    - run: solana config set --url localhost
      shell: bash
