name: Setup All
description: Setup All for testing
runs:
  using: "composite"
  runs-on: ubuntu-latest
  steps:
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - run: rustc --version
      shell: bash
    - run: echo "rust all setup"
      shell: bash
