name: Localnet Tests
on:
  workflow_call

jobs:
  setup_env:
    # uses: ./.github/actions/setup-all
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - run: echo "Setup complete workflow_call"
        shell: bash

    