name: Localnet Tests
on:
  workflow_call:
    inputs:
      cache:
        type: boolean
        required: true
      solana_cli_version:
        type: string
        required: true
      node_version:
        type: string
        required: true
      cargo_profile:
        type: string
        required: true
      anchor_binary_name:
        type: string
        required: true
      anchor_version:
        type: string
        required: true
    

env:
  CACHE: inputs.cache
  SOLANA_CLI_VERSION: ${{ inputs.solana_cli_version }}
  NODE_VERSION: ${{ inputs.node_version }}
  CARGO_PROFILE: ${{ inputs.cargo_profile }}
  ANCHOR_BINARY_NAME: ${{ inputs.anchor_binary_name }}
  ANCHOR_VERSION: ${{ inputs.anchor_version }}  
  CARGO_CACHE_PATH: |
    ~/.cargo/bin/
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/
    ./target/

jobs:
  tests:
    name: Test-env set u
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - run: rustc --version
    
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/
      - run: 'echo "anchor version: ${{ env.ANCHOR_VERSION }}'
      - run: 'echo "node version before:"'
      - run: node --version
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: 'echo "node version after:"'
      - run: node --version
      # - uses: ./.github/actions/setup-solana/
      # - uses: ./.github/actions/setup-node/
    
      # - run: cargo build
      # - run: cargo fmt -- --check
      # - run: cargo clippy --all-targets -- -D warnings
      # - run: cargo test  
      - run: rustup --version
    