name: Mi Reusable Tests

on:
  workflow_call:
    inputs:
      cache:
        required: true
        type: boolean
      solana_cli_version:
        required: true
        type: string
      node_version:
        required: true
        type: string
      anchor_version:
        required: true
        type: string
      cargo_profile:
        required: true
        type: string
      anchor_binary_name:
        required: true
        type: string
env:
  CACHE: ${{ inputs.cache }}
  SOLANA_CLI_VERSION: ${{ inputs.solana_cli_version }}
  NODE_VERSION: ${{ inputs.node_version }}
  CARGO_PROFILE: ${{ inputs.cargo_profile }}
  ANCHOR_BINARY_NAME: ${{ inputs.anchor_binary_name }}
  ANCHOR_VERSION: ${{ inputs.anchor_version }}  
  CARGO_CACHE_PATH: |
    ~/.cargo/bin/
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/
    ./target/
      
jobs:
  setup-anchor-cli:
    name: Setup Anchor cli
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/
      - name: before anchor install check cache hit  
        run: 'echo Cache hit: "${{ steps.cache-anchor.outputs.cache-hit }}"'
      - uses: actions/cache@v3
        if: ${{ env.CACHE != 'false' }}
        name: Cache Cargo registry + index
        id: cache-anchor
        with:
          path: ${{ env.CARGO_CACHE_PATH }}
          key: cargo-${{ runner.os }}-${{ env.CARGO_PROFILE }}-anchor-${{ hashFiles('**/Cargo.lock') }}
      - name: after anchor install check cache hit  
        run: 'echo Cache hit: "${{ steps.cache-anchor.outputs.cache-hit }}"'

