name: Reusable Tests

on:
  workflow_call:
    inputs:
      cache:
        type: boolean
        required: true
      solana_cli_version:
        type: string
        required: true
      node_version:
        type: string
        required: true
      cargo_profile:
        type: string
        required: true
      anchor_binary_name:
        type: string
        required: true


env:
  CACHE: ${{ inputs.cache }}
  SOLANA_CLI_VERSION: ${{ inputs.solana_cli_version }}
  NODE_VERSION: ${{ inputs.node_version }}
  CARGO_PROFILE: ${{ inputs.cargo_profile }}
  ANCHOR_BINARY_NAME: ${{ inputs.anchor_binary_name }}
  CARGO_CACHE_PATH: |
    ~/.cargo/bin/
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/
    ./target/ 

jobs:
  debug_test:
    name: Debug Tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ env.CACHE }}" 
      - run: echo "Next step"
  
  setup-anchor-cli:
    name: Setup Anchor CLI
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/
      - uses: actions/cache@v3
        if: ${{ env.CACHE != 'false' }}
        name: Cache Cargo registry + index
        id: cache-anchor
        with:
          path: ${{ env.CARGO_CACHE_PATH }}
          key: cargo-${{ runner.os }}-${{ env.CARGO_PROFILE }}-anchor-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo install --path cli anchor-cli --locked --force --debug
        if: env.CARGO_PROFILE == 'debug'
      - run: cargo install --path cli anchor-cli --locked --force
        if: env.CARGO_PROFILE != 'debug'
      - run: chmod +x ~/.cargo/bin/anchor    
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ANCHOR_BINARY_NAME }}
          path: ~/.cargo/bin/anchor

      - uses: ./.github/actions/git-diff/
       

  test-programs:
    needs: setup-anchor-cli
    name: Test ${{matrix.node.path}}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node:
          - cmd: anchor test --skip-lint
            path: tests/sysvars
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/
      - uses: ./.github/actions/setup-ts/
      - uses: ./.github/actions/setup-solana/
      
      - uses: actions/cache@v3
        if: ${{ env.CACHE != 'false' }}
        name: Cache Cargo registry + index
        id: cache-anchor
        with:
          path: ${{ env.CARGO_CACHE_PATH }}
          key: cargo-${{ runner.os }}-${{ env.CARGO_PROFILE }}-anchor-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.ANCHOR_BINARY_NAME }}
          path: ~/.cargo/bin/
      - run: chmod +x ~/.cargo/bin/anchor       

      - uses: actions/cache@v3
        if: ${{ env.CACHE != 'false' }}
        name: Cache ${{ matrix.node.path }} target
        id: cache-test-target
        with:
          path: ${{ matrix.node.path }}/target
          key: cargo-${{ runner.os }}-${{ matrix.node.path }}-${{ env.ANCHOR_VERSION }}-${{ env.SOLANA_CLI_VERSION }}-${{ hashFiles('**/Cargo.lock') }}
      
      - run: ${{ matrix.node.cmd }}
        name: Test ${{ matrix.node.path }} program test

      - uses: ./.github/actions/git-diff/   
