name: Tests

on:
  push:
    branches:
      - devops/actions  
jobs:
  tests:
    name: Reusable Tests
    uses: ./.github/workflows/reusable-tests.yml
    with:
      cache: false
      solana_cli_version: 2.1.0
      node_version: 20.16.0
      cargo_profile: debug
      anchor_binary_name: anchor_binary
