name: Tests

on:
  push:
    branches:
      - devops/actions  
jobs:
  setup_env:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/localnet-tests.yml
      - run: echo "Setup complete"
     
 
